# Generated by Django 5.0.1 on 2024-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_financialgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000),
        ),
    ]
